name = "wires-create"
author = "marshmallow, michaili"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dfa2c2a5dfe6a46fa1349e1ab9652d1acd4352a8c757ac37a000bacbd74f6c5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
unsup = "1.2.4"

[options]
datapack-folder = "datapacks"
