name = "wires-create"
author = "marshmallow, michaili"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b293e798f4fe2c81629ab895f2a7ccb23c2c493979d15040884975865a8bc8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "datapacks"
