name = "wires-create"
author = "marshmallow, michaili"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81bc75a4b4fc321a08e7c409412b9573dbd4e034765cbe64b8f41149f22cd885"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "datapacks"
